-- ==============================================================================
-- Ironcladgroup - Supabase/PostgreSQL Database Schema
-- ==============================================================================

-- 1. AUXILIARY TABLES (LOOKUPS)
-- Creating all lookup tables first so foreign keys resolve correctly.

CREATE TABLE ls_origem (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_status (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_priority (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, color VARCHAR(7) DEFAULT '#94a3b8');
CREATE TABLE ls_county (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, state VARCHAR(2) DEFAULT 'FL');
CREATE TABLE ls_auction_type (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_auction_model (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_property_type (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_fema (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_wetlands (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_debit (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_gismap (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_property_access (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_road_access (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_ref_construction (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);

-- Optional: Initial Seed Data for Statuses and Priorities (Examples)
-- INSERT INTO ls_status (name) VALUES ('Auction'), ('Property'), ('Archived');
-- INSERT INTO ls_priority (name) VALUES ('High'), ('Medium'), ('Low'), ('No Interest');


-- ==============================================================================
-- 2. MAIN TABLE: ls_assets
-- ==============================================================================

CREATE TABLE ls_assets (
    -- Identification (autonumber as per request)
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ref_id NUMERIC,
    
    -- Foreign Keys to Auxiliary Tables
    origem_id UUID REFERENCES ls_origem(id) ON DELETE SET NULL,
    status_id UUID REFERENCES ls_status(id) ON DELETE SET NULL,
    priority_id UUID REFERENCES ls_priority(id) ON DELETE SET NULL,
    county_id UUID REFERENCES ls_county(id) ON DELETE SET NULL,
    auction_type_id UUID REFERENCES ls_auction_type(id) ON DELETE SET NULL,
    auction_model_id UUID REFERENCES ls_auction_model(id) ON DELETE SET NULL,
    property_type_id UUID REFERENCES ls_property_type(id) ON DELETE SET NULL,
    fema_id UUID REFERENCES ls_fema(id) ON DELETE SET NULL,
    wetlands_id UUID REFERENCES ls_wetlands(id) ON DELETE SET NULL,
    debit_id UUID REFERENCES ls_debit(id) ON DELETE SET NULL,
    gismap_id UUID REFERENCES ls_gismap(id) ON DELETE SET NULL,
    prop_access_id UUID REFERENCES ls_property_access(id) ON DELETE SET NULL,
    road_access_id UUID REFERENCES ls_road_access(id) ON DELETE SET NULL,
    ref_construction_id UUID REFERENCES ls_ref_construction(id) ON DELETE SET NULL,

    -- Legal & Location
    record_type VARCHAR(50) DEFAULT 'AUCTION',
    address VARCHAR(255),
    parcel_number VARCHAR(255),
    case_number VARCHAR(255),
    legal_description VARCHAR(255),
    coordinates VARCHAR(255),
    zoning VARCHAR(255),
    
    -- Metrics & Links
    size NUMERIC,
    link_regrid TEXT,
    observation TEXT,
    surrounds TEXT,
    link_sources TEXT,
    link_house_sources TEXT,
    link_video TEXT,
    link_earth TEXT,
    
    -- Financials & Bids
    market_value NUMERIC,
    annual_tax NUMERIC,
    open_bid NUMERIC,
    max_bid NUMERIC,
    max_bid_internal NUMERIC,
    min_bid NUMERIC,
    
    -- Appraisals
    appraisal_min NUMERIC,
    appraisal_avg NUMERIC,
    appraisal_max NUMERIC,
    county_appraisal NUMERIC,
    online_appraisal NUMERIC,
    sqft_price_reference NUMERIC,
    house_price NUMERIC,
    
    -- Dates (Stored with timezone for safety)
    auction_date TIMESTAMP WITH TIME ZONE,
    upset_date TIMESTAMP WITH TIME ZONE,
    acquisition_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Audit & Control (References Supabase Auth Users)
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    
    -- Booleans
    inperson_visit BOOLEAN DEFAULT FALSE,
    corner_lot BOOLEAN DEFAULT FALSE
);


-- ==============================================================================
-- 3. AUTOMATIC UPDATED_AT TRIGGER
-- ==============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_ls_assets_updated_at
BEFORE UPDATE ON ls_assets
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ==============================================================================
-- 4. AUDIT LOG TABLE
-- ==============================================================================

CREATE TABLE ls_audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id BIGINT REFERENCES ls_assets(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    field_name VARCHAR(255) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 5. RLS (Row Level Security) - Basics (Optional to enable)
-- ==============================================================================
-- ALTER TABLE ls_assets ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ls_audit_logs ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 6. AMENITIES MODULE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ls_amenity_category (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID
);

CREATE TABLE IF NOT EXISTS ls_amenity_type (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID REFERENCES ls_amenity_category(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID
);

CREATE TABLE IF NOT EXISTS ls_asset_amenities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id BIGINT REFERENCES ls_assets(id) ON DELETE CASCADE,
    amenity_type_id UUID REFERENCES ls_amenity_type(id) ON DELETE CASCADE,
    distance_miles DECIMAL(10,2),
    time_minutes INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID
);

-- ==============================================================================
-- 7. ACCESS CONTROL MODULE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ls_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ls_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID REFERENCES ls_profiles(id) ON DELETE CASCADE,
    resource_key VARCHAR(255) NOT NULL, -- e.g., 'page:auctions', 'tab:financials'
    can_view BOOLEAN DEFAULT TRUE,
    can_edit BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(profile_id, resource_key)
);

CREATE TABLE IF NOT EXISTS ls_user_profiles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    profile_id UUID REFERENCES ls_profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Triggers for updated_at
CREATE TRIGGER tr_ls_profiles_updated_at BEFORE UPDATE ON ls_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER tr_ls_user_profiles_updated_at BEFORE UPDATE ON ls_user_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ==============================================================================
-- 8. INITIAL SEED (Access Control)
-- ==============================================================================

-- Profiles
INSERT INTO ls_profiles (name, description) VALUES 
('Administrator', 'Full access to all modules and editing capabilities.'),
('Analyst', 'Can view and edit assets, but limited access to sensitive tabs.'),
('Viewer', 'Read-only access to specific public modules.');

-- ==============================================================================
-- 9. USER METADATA (Public Mirror of auth.users)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ls_users_metadata (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Trigger for updated_at
CREATE TRIGGER tr_ls_users_metadata_updated_at BEFORE UPDATE ON ls_users_metadata FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Note: In a real environment, you would add a Database Trigger in Supabase 
-- to automatically populate this table when a user signs up.
