-- ==============================================================================
-- Ironcladgroup - Supabase/PostgreSQL Database Schema
-- ==============================================================================

-- 1. AUXILIARY TABLES (LOOKUPS)
-- Creating all lookup tables first so foreign keys resolve correctly.

CREATE TABLE ls_origem (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_status (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_priority (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, color VARCHAR(7) DEFAULT '#94a3b8');
CREATE TABLE ls_county (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, state VARCHAR(2) DEFAULT 'FL');
CREATE TABLE ls_auction_type (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_auction_model (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_property_type (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_fema (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_wetlands (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_debit (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_gismap (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_property_access (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_road_access (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);
CREATE TABLE ls_ref_construction (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL);

-- Optional: Initial Seed Data for Statuses and Priorities (Examples)
-- INSERT INTO ls_status (name) VALUES ('Auction'), ('Property'), ('Archived');
-- INSERT INTO ls_priority (name) VALUES ('High'), ('Medium'), ('Low'), ('No Interest');


-- ==============================================================================
-- 2. MAIN TABLE: ls_assets
-- ==============================================================================

CREATE TABLE ls_assets (
    -- Identification (autonumber as per request)
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ref_id NUMERIC,
    
    -- Foreign Keys to Auxiliary Tables
    origem_id UUID REFERENCES ls_origem(id) ON DELETE SET NULL,
    status_id UUID REFERENCES ls_status(id) ON DELETE SET NULL,
    priority_id UUID REFERENCES ls_priority(id) ON DELETE SET NULL,
    county_id UUID REFERENCES ls_county(id) ON DELETE SET NULL,
    auction_type_id UUID REFERENCES ls_auction_type(id) ON DELETE SET NULL,
    auction_model_id UUID REFERENCES ls_auction_model(id) ON DELETE SET NULL,
    property_type_id UUID REFERENCES ls_property_type(id) ON DELETE SET NULL,
    fema_id UUID REFERENCES ls_fema(id) ON DELETE SET NULL,
    wetlands_id UUID REFERENCES ls_wetlands(id) ON DELETE SET NULL,
    debit_id UUID REFERENCES ls_debit(id) ON DELETE SET NULL,
    gismap_id UUID REFERENCES ls_gismap(id) ON DELETE SET NULL,
    prop_access_id UUID REFERENCES ls_property_access(id) ON DELETE SET NULL,
    road_access_id UUID REFERENCES ls_road_access(id) ON DELETE SET NULL,
    ref_construction_id UUID REFERENCES ls_ref_construction(id) ON DELETE SET NULL,

    -- Legal & Location
    record_type VARCHAR(50) DEFAULT 'AUCTION',
    address VARCHAR(255),
    parcel_number VARCHAR(255),
    case_number VARCHAR(255),
    legal_description TEXT,
    coordinates VARCHAR(255),
    zoning VARCHAR(255),
    
    -- Metrics & Links
    size NUMERIC,
    link_regrid TEXT,
    observation TEXT,
    surrounds TEXT,
    link_sources TEXT,
    link_house_sources TEXT,
    link_video TEXT,
    link_earth TEXT,
    tax_deed TEXT,
    warranty_deed TEXT,
    survey TEXT,
    site_plan TEXT,
    
    -- Financials & Bids
    market_value NUMERIC,
    annual_tax NUMERIC,
    open_bid NUMERIC,
    max_bid NUMERIC,
    max_bid_internal NUMERIC,
    min_bid NUMERIC,
    
    -- Appraisals
    appraisal_min NUMERIC,
    appraisal_avg NUMERIC,
    appraisal_max NUMERIC,
    county_appraisal NUMERIC,
    online_appraisal NUMERIC,
    sqft_price_reference NUMERIC,
    house_price NUMERIC,
    
    -- Dates (Stored with timezone for safety)
    auction_date TIMESTAMP WITH TIME ZONE,
    upset_date TIMESTAMP WITH TIME ZONE,
    acquisition_date TIMESTAMP WITH TIME ZONE,
    tax_pay_dead TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Audit & Control (References Supabase Auth Users)
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    
    -- Booleans
    inperson_visit BOOLEAN DEFAULT FALSE,
    corner_lot BOOLEAN DEFAULT FALSE
    );

-- ==============================================================================
-- 3. NEW ENUM TYPES FOR FINANCIAL FIELDS
-- ==============================================================================

CREATE TYPE sale_status_enum AS ENUM ('Pending', 'Listed', 'Awaiting Purchase');
CREATE TYPE improvements_enum AS ENUM ('No Improvements', 'Well only', 'Septic only', 'Well & Septic');
CREATE TYPE mh_allowed_enum AS ENUM ('Yes', 'No', 'Modular Only');

-- ==============================================================================
-- 4. ALTER TABLE ls_assets ADD NEW COLUMNS
-- ==============================================================================

ALTER TABLE ls_assets
  ADD COLUMN IF NOT EXISTS warrantydeedtransfer NUMERIC,
  ADD COLUMN IF NOT EXISTS tg_warrantydeedtransfer BOOLEAN,
  ADD COLUMN IF NOT EXISTS titleclaim_action NUMERIC,
  ADD COLUMN IF NOT EXISTS tg_titleclaim_action BOOLEAN,
  ADD COLUMN IF NOT EXISTS surveyor NUMERIC,
  ADD COLUMN IF NOT EXISTS tg_surveyor BOOLEAN,
  ADD COLUMN IF NOT EXISTS land_clearing NUMERIC,
  ADD COLUMN IF NOT EXISTS tg_land_clearing BOOLEAN,
  ADD COLUMN IF NOT EXISTS fencing_gate NUMERIC,
  ADD COLUMN IF NOT EXISTS tg_fencing_gate BOOLEAN,
  ADD COLUMN IF NOT EXISTS preapproval_review NUMERIC,
  ADD COLUMN IF NOT EXISTS tg_preapproval_review BOOLEAN,
  ADD COLUMN IF NOT EXISTS investment_total NUMERIC,
  ADD COLUMN IF NOT EXISTS sale_status sale_status_enum,
  ADD COLUMN IF NOT EXISTS improvements improvements_enum,
  ADD COLUMN IF NOT EXISTS mh_allowed mh_allowed_enum,
  ADD COLUMN IF NOT EXISTS utilities TEXT;


-- ==============================================================================
-- 3. AUTO ref_id TRIGGER (assigns sequential ref_id per record_type on INSERT)
-- ==============================================================================

CREATE OR REPLACE FUNCTION assign_ref_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.ref_id IS NULL THEN
    SELECT COALESCE(MAX(ref_id), 0) + 1
      INTO NEW.ref_id
      FROM ls_assets
     WHERE record_type = NEW.record_type;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_assign_ref_id
BEFORE INSERT ON ls_assets
FOR EACH ROW EXECUTE FUNCTION assign_ref_id();


-- ==============================================================================
-- 4. AUTOMATIC UPDATED_AT TRIGGER
-- ==============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_ls_assets_updated_at
BEFORE UPDATE ON ls_assets
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


-- ==============================================================================
-- 4. AUDIT LOG TABLE
-- ==============================================================================

CREATE TABLE ls_audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id BIGINT REFERENCES ls_assets(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    field_name VARCHAR(255) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 5. RLS (Row Level Security) - Basics (Optional to enable)
-- ==============================================================================
-- ALTER TABLE ls_assets ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE ls_audit_logs ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 6. AMENITIES MODULE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ls_amenity_category (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID
);

CREATE TABLE IF NOT EXISTS ls_amenity_type (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID REFERENCES ls_amenity_category(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID
);

CREATE TABLE IF NOT EXISTS ls_asset_amenities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id BIGINT REFERENCES ls_assets(id) ON DELETE CASCADE,
    amenity_type_id UUID REFERENCES ls_amenity_type(id) ON DELETE CASCADE,
    distance_miles DECIMAL(10,2),
    time_minutes INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID
);

-- ==============================================================================
-- 7. ACCESS CONTROL MODULE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ls_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ls_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID REFERENCES ls_profiles(id) ON DELETE CASCADE,
    resource_key VARCHAR(255) NOT NULL, -- e.g., 'page:auctions', 'tab:financials'
    can_view BOOLEAN DEFAULT TRUE,
    can_edit BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(profile_id, resource_key)
);

CREATE TABLE IF NOT EXISTS ls_user_profiles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    profile_id UUID REFERENCES ls_profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Triggers for updated_at
CREATE TRIGGER tr_ls_profiles_updated_at BEFORE UPDATE ON ls_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER tr_ls_user_profiles_updated_at BEFORE UPDATE ON ls_user_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ==============================================================================
-- 8. INITIAL SEED (Access Control)
-- ==============================================================================

-- Profiles
INSERT INTO ls_profiles (name, description) VALUES 
('Administrator', 'Full access to all modules and editing capabilities.'),
('Analyst', 'Can view and edit assets, but limited access to sensitive tabs.'),
('Viewer', 'Read-only access to specific public modules.');

-- ==============================================================================
-- 9. USER METADATA (Public Mirror of auth.users)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ls_users_metadata (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Trigger for updated_at
CREATE TRIGGER tr_ls_users_metadata_updated_at BEFORE UPDATE ON ls_users_metadata FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- User type: 'employee' (internal staff) or 'partner' (external partners)
ALTER TABLE ls_users_metadata
ADD COLUMN IF NOT EXISTS user_type VARCHAR(20) DEFAULT 'employee'
CHECK (user_type IN ('employee', 'partner'));

-- ==============================================================================
-- PROPERTY OWNERSHIP
-- owner_type = 'ironclad' (default) or 'partner'
-- owner_partner_id: NULL when IronClad, UUID of ls_users_metadata when partner
-- DEFAULT 'ironclad' ensures all existing properties are assigned to IronClad automatically.
-- ==============================================================================

ALTER TABLE ls_assets
  ADD COLUMN IF NOT EXISTS owner_type VARCHAR(20) DEFAULT 'ironclad'
    CHECK (owner_type IN ('ironclad', 'partner')),
  ADD COLUMN IF NOT EXISTS owner_partner_id UUID
    REFERENCES ls_users_metadata(id) ON DELETE SET NULL;

-- Note: In a real environment, you would add a Database Trigger in Supabase
-- to automatically populate this table when a user signs up.

-- ==============================================================================
-- 10. INTERNAL REQUESTS MODULE (Helpdesk/Tickets)
-- ==============================================================================

-- Lookup: Categories
CREATE TABLE IF NOT EXISTS ls_request_category (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    color VARCHAR(7) DEFAULT '#94a3b8'
);

-- Lookup: Priorities (Includes SLA config)
CREATE TABLE IF NOT EXISTS ls_request_priority (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    color VARCHAR(7) DEFAULT '#94a3b8',
    sla_hours INTEGER NOT NULL DEFAULT 24  -- SLA in running hours: Critical=4, High=24, Medium=48, Low=72
);

-- Lookup: Status
CREATE TABLE IF NOT EXISTS ls_request_status (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    color VARCHAR(7) DEFAULT '#94a3b8',
    is_closed BOOLEAN DEFAULT FALSE
);

-- Main Requests Table
CREATE TABLE IF NOT EXISTS ls_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    
    requester_id UUID REFERENCES ls_users_metadata(id) ON DELETE SET NULL,
    assignee_id UUID REFERENCES ls_users_metadata(id) ON DELETE SET NULL,
    
    -- Optional Link to a Property (Asset)
    asset_id BIGINT REFERENCES ls_assets(id) ON DELETE SET NULL,
    
    category_id UUID REFERENCES ls_request_category(id) ON DELETE SET NULL,
    priority_id UUID REFERENCES ls_request_priority(id) ON DELETE SET NULL,
    status_id UUID REFERENCES ls_request_status(id) ON DELETE SET NULL,
    
    due_date TIMESTAMP WITH TIME ZONE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER tr_ls_requests_updated_at BEFORE UPDATE ON ls_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Trigger Function to auto-calculate due_date based on SLA (running hours)
CREATE OR REPLACE FUNCTION calculate_request_due_date()
RETURNS TRIGGER AS $$
DECLARE
    v_sla_hours INTEGER;
BEGIN
    -- Only calculate if due_date is not manually set
    IF NEW.due_date IS NULL AND NEW.priority_id IS NOT NULL THEN
        SELECT sla_hours INTO v_sla_hours FROM ls_request_priority WHERE id = NEW.priority_id;
        IF v_sla_hours IS NOT NULL THEN
            NEW.due_date := CURRENT_TIMESTAMP + make_interval(hours => v_sla_hours);
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_ls_requests_due_date
BEFORE INSERT OR UPDATE OF priority_id ON ls_requests
FOR EACH ROW EXECUTE FUNCTION calculate_request_due_date();

-- Comments & Audit Timeline
CREATE TABLE IF NOT EXISTS ls_request_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    request_id BIGINT REFERENCES ls_requests(id) ON DELETE CASCADE,
    author_id UUID REFERENCES ls_users_metadata(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Notifications (In-App Alerts)
CREATE TABLE IF NOT EXISTS ls_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES ls_users_metadata(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    link VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- IMPORTANT: Enable Realtime for Notifications so the Bell updates automatically
ALTER PUBLICATION supabase_realtime ADD TABLE ls_notifications;

-- Trigger to auto-create notification when assigned
CREATE OR REPLACE FUNCTION notify_on_request_assignment()
RETURNS TRIGGER AS $$
BEGIN
    -- If newly assigned or assignee changed
    IF NEW.assignee_id IS NOT NULL AND (TG_OP = 'INSERT' OR OLD.assignee_id IS DISTINCT FROM NEW.assignee_id) THEN
        INSERT INTO ls_notifications (user_id, title, message, link)
        VALUES (
            NEW.assignee_id,
            'New Request Assigned',
            'You have been assigned to: ' || NEW.title,
            '/requests/' || NEW.id
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_ls_requests_assignment
AFTER INSERT OR UPDATE OF assignee_id ON ls_requests
FOR EACH ROW EXECUTE FUNCTION notify_on_request_assignment();

-- Initial Seed for Requests Module
-- INSERT INTO ls_request_category (name) VALUES ('General Support'), ('Property Valuation'), ('Legal Review'), ('Financial Approval');
-- INSERT INTO ls_request_priority (name, sla_days, color) VALUES ('Low', 5, '#22c55e'), ('Medium', 3, '#eab308'), ('High', 2, '#f97316'), ('Critical', 1, '#ef4444');
-- INSERT INTO ls_request_status (name, color, is_closed) VALUES ('Open', '#3b82f6', FALSE), ('In Progress', '#eab308', FALSE), ('Waiting on Requester', '#f97316', FALSE), ('Resolved', '#22c55e', TRUE), ('Cancelled', '#94a3b8', TRUE);

-- ==============================================================================
-- 11. TAX MODULE
-- Values for vigency, recurrence, status and type_tax are stored as plain TEXT.
-- Options are managed in the frontend code (no lookup tables needed).
-- ==============================================================================

CREATE TABLE IF NOT EXISTS ls_asset_tax (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id BIGINT REFERENCES ls_assets(id) ON DELETE CASCADE,
    due_date DATE,
    pay_date DATE,
    received_date DATE,
    perc_iron NUMERIC,
    perc_inv NUMERIC,
    link_proof TEXT,
    link_bill TEXT,
    link_advalorem TEXT,
    value NUMERIC,
    vigency VARCHAR(10),    -- '2025' | '2026' | '2027' | '2028' | '2029' | '2030'
    recurrence VARCHAR(20), -- 'Annual' | 'Single'
    status VARCHAR(20),     -- 'On Time' | 'Over Due'
    type_tax VARCHAR(30),   -- 'Annual Tax' | 'Fees' | 'HOA/POA'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TRIGGER tr_ls_asset_tax_updated_at
BEFORE UPDATE ON ls_asset_tax
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Grant tab:tax permission to all existing profiles
INSERT INTO ls_permissions (profile_id, resource_key, can_view, can_edit)
SELECT id, 'tab:tax', true, true  FROM ls_profiles WHERE name = 'Administrator'
ON CONFLICT (profile_id, resource_key) DO NOTHING;

INSERT INTO ls_permissions (profile_id, resource_key, can_view, can_edit)
SELECT id, 'tab:tax', true, false FROM ls_profiles WHERE name = 'Analyst'
ON CONFLICT (profile_id, resource_key) DO NOTHING;

INSERT INTO ls_permissions (profile_id, resource_key, can_view, can_edit)
SELECT id, 'tab:tax', true, false FROM ls_profiles WHERE name = 'Viewer'
ON CONFLICT (profile_id, resource_key) DO NOTHING;
