-- ============================================================
-- PATCH 21 — Log de Atividade / Produtividade ("activity_log")
--
-- Registra QUE uma acao aconteceu (tabela + operacao + quem + quando),
-- sem guardar valores antigo/novo nem qual linha foi alterada -- e' um
-- relatorio de produtividade, nao uma trilha de auditoria com diff.
--
-- Dois mecanismos de captura:
--   1) TRIGGER generico nas tabelas escritas DIRETO pelo navegador
--      (com a sessao do proprio usuario) -- auth.uid() funciona sozinho,
--      cobre campos/telas novas no futuro sem precisar tocar em nada.
--   2) Chamada explicita (1 linha) nas rotas de servidor que usam
--      service_role (Manager, Access, Users, Bids refresh) -- essas
--      rotas ja autenticam o usuario pra checar permissao, entao ja
--      sabem quem e; auth.uid() fica nulo nesse caminho, entao o
--      trigger nao serviria ali. Ver src/lib/activity.ts.
--
-- Escopo combinado com o usuario: SEM DELETE nas tabelas de negocio
-- (Property/Auction/Tax/Amenity/Requests) -- so INSERT/UPDATE. Exclusao
-- de usuario (Access) continua coberta, e' uma acao administrativa
-- distinta, nao a exclusao de um registro de negocio.
--
-- changed_by aponta pra auth.users com ON DELETE SET NULL (nao CASCADE):
-- se um usuario for removido do time, o historico de produtividade dele
-- permanece, so perde o vinculo direto.
--
-- Consulta so por SQL Editor por enquanto (RLS habilitado, sem policy).
-- Ver: src/lib/activity.ts
--      scripts/queries/activity_log.sql
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS activity_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  TEXT NOT NULL,
    operation   TEXT NOT NULL,
    changed_by  UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_log_user_time
  ON activity_log (changed_by, changed_at DESC);

ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
-- Sem policy de SELECT de proposito: so service_role (rotas) e o papel
-- postgres (SQL Editor) leem/escrevem. Mesmo padrao do user_activity.

-- ----------------------------------------------------------
-- Funcao generica do trigger. SECURITY DEFINER pra poder inserir em
-- activity_log apesar de RLS (mesmo truque de is_employee()); auth.uid()
-- continua refletindo o usuario que fez a chamada, independente disso.
-- So grava quando ha um usuario autenticado (auth.uid() nao nulo) --
-- escritas de service_role em tabelas com este trigger (ex: o Import
-- de Listings do COSL gravando em ls_assets) ficam de fora aqui, ja
-- que nao sao acao de pessoa.
-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION log_activity()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF auth.uid() IS NOT NULL THEN
        INSERT INTO activity_log (table_name, operation, changed_by)
        VALUES (TG_TABLE_NAME, TG_OP, auth.uid());
    END IF;
    RETURN NULL; -- AFTER trigger: valor de retorno e' ignorado
END;
$$;

-- ----------------------------------------------------------
-- Aplica o trigger nas tabelas escritas direto pelo navegador.
-- Sem DELETE (escopo combinado).
-- ----------------------------------------------------------
DO $$
DECLARE
    t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'ls_assets',
        'ls_asset_marketing',
        'ls_asset_tax',
        'ls_asset_amenities',
        'ls_requests',
        'ls_request_comments'
    ]
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_log_activity ON %I;', t);
        EXECUTE format(
            'CREATE TRIGGER trg_log_activity AFTER INSERT OR UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION log_activity();', t
        );
    END LOOP;
END $$;

COMMIT;
