-- ============================================================
-- PATCH 19 — Rastreamento de Atividade do Usuario ("user-activity")
--
-- Mede quanto tempo cada usuario fica com o sistema ABERTO, VISIVEL e
-- com atividade (mouse/teclado nos ultimos 5 min). O cliente manda um
-- "ping" a cada 60s por /api/activity/ping; o servidor funde pings em
-- blocos continuos (gap > 10 min = bloco novo).
--
-- SEM painel no app. Consulta so via SQL Editor / psql.
-- Ver: src/components/ActivityHeartbeat.tsx
--      src/app/api/activity/ping/route.ts
--      scripts/queries/user_activity.sql   (consultas prontas)
-- ============================================================

BEGIN;

-- ----------------------------------------------------------
-- Tabela: um bloco = um periodo continuo de trabalho
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_activity (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_ping_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    ping_count    INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_user_activity_user_last_ping
  ON user_activity (user_id, last_ping_at DESC);

-- ----------------------------------------------------------
-- RLS: HABILITADO e SEM policy -> nem anon nem authenticated
-- conseguem ler/escrever. service_role (a rota /api/activity/ping)
-- e o papel postgres (SQL Editor) ignoram RLS.
-- ----------------------------------------------------------
ALTER TABLE user_activity ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------
-- Funcao de ping: estende o bloco recente do usuario, ou abre um novo.
-- MERGE_GAP = 10 minutos. SECURITY INVOKER (roda como service_role).
-- ----------------------------------------------------------
CREATE OR REPLACE FUNCTION record_activity_ping(p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    UPDATE user_activity u
       SET last_ping_at = now(),
           ping_count   = ping_count + 1
     WHERE u.id = (
       SELECT id FROM user_activity
        WHERE user_id = p_user_id
          AND last_ping_at >= now() - INTERVAL '10 minutes'
        ORDER BY last_ping_at DESC
        LIMIT 1
     );

    IF NOT FOUND THEN
        INSERT INTO user_activity (user_id) VALUES (p_user_id);
    END IF;
END;
$$;

REVOKE ALL ON FUNCTION record_activity_ping(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION record_activity_ping(UUID) TO service_role;

COMMIT;
